version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: 'sifos'
      POSTGRES_USER: 'sifos'
      POSTGRES_PASSWORD: 'A12345678'
    ports:
      - "5432:5432"
  web:
    env_file:
        - .env.example
    restart: on-failure
    build: .
    command: sh start.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db